services:
    zookeaper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        container_name: example-zookeaper
    kafka:
        image: wurstmeister/kafka
        hostname: kafka
        ports:
            - "9092:9092"
        links:
            - zookeaper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "localhost"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: "zookeaper:2181"
            KAFKA_CREATE_TOPICS: "example-topic:2:1"
        depends_on:
            - zookeaper
        container_name: example-kafka
    