services:
  postgres:
    image: postgres
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    container_name: db
    restart: unless-stopped